
output_dir: ./scans

masscan:
  ports_common: "21,22,23,25,53,80,110,111,123,135,137,139,143,161,389,445,465,500,514,587,593,631,636,873,902,912,1025,1352,1433,1521,2049,2375,2376,2380,2480,27017,3000,3128,3260,3306,3389,5000,5432,5601,5672,5900,5985,5986,6379,7001,7002,8000,8008,8080,8081,8088,8443,8500,8529,8530,8600,8888,9000,9092,9200,9300,9418,11211,27018,27019"
  ports_default: "1-65535"
  rate: 2000
  timeout: 300

nmap:
  timing: T3
  timeout: 900

nuclei:
  timeout: 900

report:
  file: report.html
